title: Yousef Sadatmand # Yousef Sadatmand (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

